### PR TITLE
team: Drop me

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
cc @Foggalong

### CODE REVIEW

**Comment by Foggalong** [comment]
@bilelmoussaoui I've not been a Numix team member for 2 years now, see [numixproject.github.io/team](https://numixproject.github.io/team.html) :wink:

**Comment by bilelmoussaoui** [comment]
but you still have merge access which I no longer do...

**Comment by Foggalong** [comment]
@bilelmoussaoui Nope, I don't! I'm not in the organisation anymore, see #26

**Comment by bilelmoussaoui** [comment]
Ah sorry for the ping then

**Comment by bilelmoussaoui** [comment]
Cc @palob, can you help with this one?

**Comment by Foggalong** [comment]
@bilelmoussaoui It's all good! Hope things are going well at Red Hat :billed_cap::heart:

**Comment by palob** [comment]
Yes, I can. Thanks for your work here, your ongoing GNOME work and all the best.

**Pull request merged**
